name: Build PR
run-name: "PR Build: #${{ github.event.pull_request.number }} (${{ github.run_attempt }}.${{ github.run_number }}) - ${{ github.event.pull_request.title }}"

on:
  pull_request_review:
    types: [submitted]    # Triggers when a PR is approved
  pull_request:
    types: [synchronize]  # Triggers when a new commit is pushed and a workflow is interrupted

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  gen-requirements:
    if: |
      github.event.review.state == 'approved' ||
      (github.event_name == 'pull_request' && github.event.pull_request.state == 'open')
    uses: "howsoai/.github/.github/workflows/compile-requirements.yml@main"
    secrets: inherit
    with:
      upstream-packages: 'amalgam-lang-py howso-engine-py'

  build:
    needs: ['gen-requirements']
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      build-type: "PR"

  xray:
    needs: ['build']
    uses: "howsoai/.github/.github/workflows/scan-pull-request.yml@main"
    secrets: inherit
    with:
      upstream-packages: 'amalgam-lang-py howso-engine-py'

  final-check:
    needs: ['build', 'gen-requirements', 'xray']
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Verify all jobs succeeded
        run: |
          # This will fail if any job didn't succeed
          if [[ ! "${{ needs.build.result }}" == "success" ]] || \
            [[ ! "${{ needs.gen-requirements.result }}" == "success" ]] || \
            [[ ! "${{ needs.xray.result }}" == "success" ]]; then
            echo "Not all required jobs succeeded"
            exit 1
          fi
          echo "All required jobs succeeded!"
